use_frameworks!

platform :ios, '10.0'

target 'MyRatingCocoapodsLibrary_Example' do
  pod 'MyRatingCocoapodsLibrary', :path => '../'

  target 'MyRatingCocoapodsLibrary_Tests' do
    inherit! :search_paths

    
  end
end
